// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mem,hls_ip_2019_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7vx485t-ffg1157-1,HLS_INPUT_CLOCK=2.780000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=1.476000,HLS_SYN_LAT=3,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=323,HLS_SYN_LUT=205,HLS_VERSION=2019_1}" *)

module mem (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        addr,
        we,
        re,
        out_r,
        out_r_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [6:0] addr;
input  [0:0] we;
input  [0:0] re;
output  [7:0] out_r;
output   out_r_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] out_r;
reg out_r_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_11001;
wire   [6:0] saved_address0;
reg    saved_ce0;
wire   [7:0] saved_q0;
wire   [6:0] saved_address1;
reg    saved_ce1;
reg    saved_we1;
reg   [6:0] tempOutAddr;
reg   [7:0] tempOutVal;
reg   [0:0] re_read_reg_133;
reg   [0:0] re_read_reg_133_pp0_iter1_reg;
reg   [0:0] re_read_reg_133_pp0_iter2_reg;
reg   [0:0] we_read_reg_137;
reg   [0:0] we_read_reg_137_pp0_iter1_reg;
reg   [0:0] we_read_reg_137_pp0_iter2_reg;
reg   [6:0] addr_read_reg_141;
reg   [6:0] addr_read_reg_141_pp0_iter1_reg;
reg   [6:0] addr_read_reg_141_pp0_iter2_reg;
reg   [6:0] saved_addr_reg_147;
reg   [6:0] saved_addr_reg_147_pp0_iter1_reg;
reg   [6:0] saved_addr_reg_147_pp0_iter2_reg;
reg   [7:0] temp_reg_153;
wire   [7:0] temp_1_fu_91_p2;
reg   [7:0] temp_1_reg_158;
reg    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln8_fu_86_p1;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln14_fu_109_p2;
wire   [7:0] zext_ln32_fu_100_p1;
reg    ap_block_pp0_stage0_01001;
wire   [7:0] zext_ln18_fu_124_p1;
wire   [7:0] zext_ln22_fu_128_p1;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to2;
reg    ap_reset_idle_pp0;
reg    ap_block_pp0;
wire    ap_enable_operation_10;
reg    ap_enable_state1_pp0_iter0_stage0;
wire    ap_enable_operation_12;
reg    ap_enable_state2_pp0_iter1_stage0;
reg    ap_enable_operation_42;
reg    ap_enable_state4_pp0_iter3_stage0;
wire    ap_enable_pp0;
reg    ap_condition_198;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 tempOutAddr = 7'd0;
#0 tempOutVal = 8'd0;
end

mem_saved #(
    .DataWidth( 8 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
saved_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(saved_address0),
    .ce0(saved_ce0),
    .q0(saved_q0),
    .address1(saved_address1),
    .ce1(saved_ce1),
    .we1(saved_we1),
    .d1(temp_1_reg_158)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        addr_read_reg_141 <= addr;
        addr_read_reg_141_pp0_iter1_reg <= addr_read_reg_141;
        re_read_reg_133 <= re;
        re_read_reg_133_pp0_iter1_reg <= re_read_reg_133;
        saved_addr_reg_147 <= zext_ln8_fu_86_p1;
        saved_addr_reg_147_pp0_iter1_reg <= saved_addr_reg_147;
        we_read_reg_137 <= we;
        we_read_reg_137_pp0_iter1_reg <= we_read_reg_137;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        addr_read_reg_141_pp0_iter2_reg <= addr_read_reg_141_pp0_iter1_reg;
        re_read_reg_133_pp0_iter2_reg <= re_read_reg_133_pp0_iter1_reg;
        saved_addr_reg_147_pp0_iter2_reg <= saved_addr_reg_147_pp0_iter1_reg;
        we_read_reg_137_pp0_iter2_reg <= we_read_reg_137_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((we_read_reg_137_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln14_fu_109_p2 == 1'd0))) begin
        tempOutAddr <= addr_read_reg_141_pp0_iter2_reg;
        tempOutVal <= temp_1_reg_158;
    end
end

always @ (posedge ap_clk) begin
    if (((we_read_reg_137_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        temp_1_reg_158 <= temp_1_fu_91_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_reg_153 <= saved_q0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_198)) begin
        if (((icmp_ln14_fu_109_p2 == 1'd1) & (we_read_reg_137_pp0_iter2_reg == 1'd1))) begin
            out_r = zext_ln22_fu_128_p1;
        end else if (((we_read_reg_137_pp0_iter2_reg == 1'd1) & (icmp_ln14_fu_109_p2 == 1'd0))) begin
            out_r = zext_ln18_fu_124_p1;
        end else if ((we_read_reg_137_pp0_iter2_reg == 1'd0)) begin
            out_r = zext_ln32_fu_100_p1;
        end else begin
            out_r = 'bx;
        end
    end else begin
        out_r = 'bx;
    end
end

always @ (*) begin
    if ((((we_read_reg_137_pp0_iter2_reg == 1'd0) & (re_read_reg_133_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((icmp_ln14_fu_109_p2 == 1'd1) & (we_read_reg_137_pp0_iter2_reg == 1'd1) & (re_read_reg_133_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((we_read_reg_137_pp0_iter2_reg == 1'd1) & (re_read_reg_133_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln14_fu_109_p2 == 1'd0)))) begin
        out_r_ap_vld = 1'b1;
    end else begin
        out_r_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        saved_ce0 = 1'b1;
    end else begin
        saved_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        saved_ce1 = 1'b1;
    end else begin
        saved_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((we_read_reg_137_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        saved_we1 = 1'b1;
    end else begin
        saved_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_198 = ((re_read_reg_133_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_01001));
end

assign ap_enable_operation_10 = (1'b1 == 1'b1);

assign ap_enable_operation_12 = (1'b1 == 1'b1);

always @ (*) begin
    ap_enable_operation_42 = (we_read_reg_137_pp0_iter2_reg == 1'd1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

always @ (*) begin
    ap_enable_state1_pp0_iter0_stage0 = ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state2_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state4_pp0_iter3_stage0 = ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign icmp_ln14_fu_109_p2 = ((temp_1_reg_158 < tempOutVal) ? 1'b1 : 1'b0);

assign saved_address0 = zext_ln8_fu_86_p1;

assign saved_address1 = saved_addr_reg_147_pp0_iter2_reg;

assign temp_1_fu_91_p2 = (temp_reg_153 + 8'd1);

assign zext_ln18_fu_124_p1 = addr_read_reg_141_pp0_iter2_reg;

assign zext_ln22_fu_128_p1 = tempOutAddr;

assign zext_ln32_fu_100_p1 = tempOutAddr;

assign zext_ln8_fu_86_p1 = addr;

endmodule //mem
